CREATE TABLE IF NOT EXISTS `micro_course_task` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `teacher_id` bigint NOT NULL COMMENT '教师ID',
  `status` varchar(32) NOT NULL DEFAULT 'queued' COMMENT 'queued/running/succeeded/failed',
  `progress` int NOT NULL DEFAULT 0 COMMENT '渲染进度 0-100',
  `title` varchar(255) DEFAULT NULL COMMENT '微课标题',
  `script_json` longtext COMMENT '脚本与分镜JSON',
  `video_url` varchar(1024) DEFAULT NULL COMMENT '生成视频URL',
  `cover_url` varchar(1024) DEFAULT NULL COMMENT '封面URL',
  `subtitle_url` varchar(1024) DEFAULT NULL COMMENT '字幕URL',
  `audio_url` varchar(1024) DEFAULT NULL COMMENT '配音URL',
  `duration_seconds` int DEFAULT NULL COMMENT '实际视频时长秒',
  `warnings_json` text COMMENT '渲染警告JSON',
  `render_stats_json` text COMMENT '渲染统计JSON',
  `params_json` longtext COMMENT '生成参数快照',
  `error_message` text COMMENT '失败原因',
  `course_id` bigint DEFAULT NULL COMMENT '发布课程ID',
  `chapter_id` bigint DEFAULT NULL COMMENT '发布章节ID',
  `resource_id` bigint DEFAULT NULL COMMENT 'AI资源ID',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_teacher_status` (`teacher_id`, `status`),
  KEY `idx_course_chapter` (`course_id`, `chapter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微课生成任务表';
