START TRANSACTION;

INSERT INTO course_graph_node
    (id, parentId, name, category, symbolSize, description, difficulty, importance, estimatedHours, teachingWeek,
     commonMistakes, teachingTips, resourceCount, exerciseCount, isCore, isKeyPoint, resourceSummary, resourceTypes,
     learnUrl, learningContent, sortOrder, createTime, updateTime, isDelete)
VALUES
    ('cs_root', NULL, '计算机科学与技术', '计算机类（0809）', 60,
     '080901，研究计算理论、计算机系统、软件开发与智能应用，是计算机类基础性专业。',
     'high', 'high', 160, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>计算机科学与技术面向计算系统、算法理论、软件开发和智能应用，培养能够进行系统分析、程序设计、计算平台构建与复杂工程问题求解的人才。</p><h3>核心方向</h3><p>程序设计、数据结构与算法、计算机组成、操作系统、数据库、计算机网络、软件工程、人工智能与系统开发。</p>',
     1, NOW(), NOW(), 0),
    ('se_root', NULL, '软件工程', '计算机类（0809）', 60,
     '080902，聚焦软件需求、设计、开发、测试、运维与项目管理。',
     'high', 'high', 150, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>软件工程关注软件全生命周期，强调工程化方法、团队协作、质量保障和复杂软件系统交付能力。</p><h3>核心方向</h3><p>需求工程、软件设计、软件测试、软件项目管理、架构设计、DevOps、云原生应用与大型软件系统开发。</p>',
     2, NOW(), NOW(), 0),
    ('ne_root', NULL, '网络工程', '计算机类（0809）', 60,
     '080903，面向计算机网络规划、建设、管理、运维与安全保障。',
     'high', 'high', 140, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>网络工程培养掌握网络体系结构、路由交换、网络安全、网络运维和工程实施能力的应用型工程人才。</p><h3>核心方向</h3><p>计算机网络、路由与交换、网络协议分析、网络安全、网络规划设计、云网络、网络自动化运维。</p>',
     3, NOW(), NOW(), 0),
    ('info_security_root', NULL, '信息安全', '计算机类（0809）', 60,
     '080904K，审批专业，面向信息系统安全、密码应用、攻防测试与安全治理。',
     'high', 'high', 150, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>信息安全面向网络空间中的数据、系统和应用安全，培养具备安全分析、防护、测评和管理能力的人才。</p><h3>核心方向</h3><p>密码学基础、网络安全、系统安全、Web安全、恶意代码分析、安全攻防、数据安全与安全管理。</p>',
     4, NOW(), NOW(), 0),
    ('iot_root', NULL, '物联网工程', '计算机类（0809）', 60,
     '080905，面向感知设备、网络通信、边缘计算与物联网应用系统开发。',
     'high', 'high', 145, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>物联网工程融合传感器、嵌入式系统、网络通信、云平台和数据处理，培养从感知层到应用层的系统设计能力。</p><h3>核心方向</h3><p>传感器技术、嵌入式开发、无线通信、物联网协议、边缘计算、IoT平台、智能硬件与行业应用。</p>',
     5, NOW(), NOW(), 0),
    ('dmt_root', NULL, '数字媒体技术', '计算机类（0809）', 60,
     '080906，融合计算机图形图像、交互技术、数字内容生产与媒体系统开发。',
     'medium', 'high', 135, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>数字媒体技术以计算机技术支撑数字内容创作和交互媒体系统开发，连接软件开发、图形图像、动画、游戏和沉浸式体验。</p><h3>核心方向</h3><p>计算机图形学、数字图像处理、三维建模、游戏开发、交互设计、虚拟现实和数字视音频处理。</p>',
     6, NOW(), NOW(), 0),
    ('intelligent_science_root', NULL, '智能科学与技术', '计算机类（0809）', 60,
     '080907T，特设专业，面向人工智能理论、智能系统和智能应用开发。',
     'high', 'high', 150, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>智能科学与技术围绕机器感知、机器学习、知识表示、智能决策和智能系统实现，培养智能技术研发和应用人才。</p><h3>核心方向</h3><p>人工智能导论、机器学习、深度学习、自然语言处理、计算机视觉、智能机器人、智能系统工程。</p>',
     7, NOW(), NOW(), 0),
    ('spatial_info_digital_tech_root', NULL, '空间信息与数字技术', '计算机类（0809）', 60,
     '080908T，特设专业，面向空间信息获取、处理、建模、可视化与数字化应用。',
     'medium', 'medium', 130, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>空间信息与数字技术融合计算机、地理信息、遥感和数字建模技术，服务空间数据处理、数字城市和行业空间智能应用。</p><h3>核心方向</h3><p>空间数据库、地理信息系统、遥感数据处理、三维建模、空间数据可视化、数字孪生与空间智能应用。</p>',
     8, NOW(), NOW(), 0),
    ('electronic_computer_engineering_root', NULL, '电子与计算机工程', '计算机类（0809）', 60,
     '080909T，特设专业，融合电子信息、计算机系统、嵌入式与软硬件协同设计。',
     'high', 'medium', 145, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>电子与计算机工程强调计算机系统与电子硬件的结合，培养具备软硬件协同开发、嵌入式系统和智能终端设计能力的人才。</p><h3>核心方向</h3><p>数字电路、计算机组成、嵌入式系统、接口技术、操作系统、软硬件协同设计、智能终端开发。</p>',
     9, NOW(), NOW(), 0),
    ('ds_root', NULL, '数据科学与大数据技术', '计算机类（0809）', 60,
     '080910T，特设专业，面向数据采集、治理、分析、建模和大数据系统开发。',
     'high', 'high', 150, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>数据科学与大数据技术围绕数据全生命周期，培养掌握数据工程、统计建模、机器学习和大数据平台开发的人才。</p><h3>核心方向</h3><p>Python数据分析、数据库、大数据存储与计算、数据挖掘、机器学习、数据可视化、数据治理与大数据平台。</p>',
     10, NOW(), NOW(), 0),
    ('cyberspace_security_root', NULL, '网络空间安全', '计算机类（0809）', 60,
     '080911TK，特设控制布点专业，面向网络空间安全战略、技术体系和综合防护。',
     'high', 'high', 155, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>网络空间安全面向国家网络安全和数字基础设施安全需求，培养具备网络攻防、系统防护、密码应用和安全治理能力的人才。</p><h3>核心方向</h3><p>网络安全、系统安全、密码学、数据安全、漏洞挖掘、网络攻防、关键信息基础设施保护与安全治理。</p>',
     11, NOW(), NOW(), 0),
    ('new_media_tech_root', NULL, '新媒体技术', '计算机类（0809）', 60,
     '080912T，特设专业，面向新媒体平台、交互传播、智能内容生产与数据驱动运营。',
     'medium', 'medium', 120, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>新媒体技术以计算机技术支撑内容生产、交互传播和平台运营，培养兼具技术开发、媒体理解和数据分析能力的人才。</p><h3>核心方向</h3><p>Web与移动开发、数字内容处理、交互技术、用户数据分析、推荐系统、新媒体平台开发和智能内容生成。</p>',
     12, NOW(), NOW(), 0),
    ('film_production_root', NULL, '电影制作', '计算机类（0809）', 60,
     '080913T，特设专业，面向数字影像制作、影视后期、虚拟拍摄与计算机视觉技术应用。',
     'medium', 'medium', 125, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>电影制作在计算机类目录下强调数字影视技术、虚拟拍摄、影像处理和视听内容生产的工程能力。</p><h3>核心方向</h3><p>数字摄影、影视后期、计算机图形图像、虚拟拍摄、视效合成、三维动画、数字音视频处理和项目制创作。</p>',
     13, NOW(), NOW(), 0),
    ('secrecy_technology_root', NULL, '保密技术', '计算机类（0809）', 60,
     '080914TK，特设控制布点专业，面向涉密信息系统、防泄密技术和保密管理支撑。',
     'high', 'medium', 135, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>保密技术面向信息系统和数据处理过程中的保密防护需求，强调防泄密、涉密系统安全和技术管理能力。</p><h3>核心方向</h3><p>信息安全基础、保密技术、数据防泄漏、安全审计、密码应用、涉密信息系统测评和保密管理支撑技术。</p>',
     14, NOW(), NOW(), 0),
    ('service_science_engineering_root', NULL, '服务科学与工程', '计算机类（0809）', 60,
     '080915T，特设专业，面向数字服务系统、服务计算、业务流程和平台工程。',
     'medium', 'medium', 120, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>服务科学与工程融合计算机、管理和工程方法，研究数字服务系统的设计、开发、运营和优化。</p><h3>核心方向</h3><p>服务计算、业务流程管理、信息系统分析、平台工程、用户体验、数据驱动服务优化和数字化服务创新。</p>',
     15, NOW(), NOW(), 0),
    ('virtual_reality_tech_root', NULL, '虚拟现实技术', '计算机类（0809）', 60,
     '080916T，特设专业，面向沉浸式系统、三维交互、实时渲染与虚拟现实应用开发。',
     'high', 'high', 140, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>虚拟现实技术面向沉浸式交互和三维数字空间构建，培养具备实时渲染、交互系统和VR/AR应用开发能力的人才。</p><h3>核心方向</h3><p>计算机图形学、三维建模、实时渲染、交互技术、空间定位、Unity/Unreal开发、VR/AR系统设计。</p>',
     16, NOW(), NOW(), 0),
    ('blockchain_engineering_root', NULL, '区块链工程', '计算机类（0809）', 60,
     '080917T，特设专业，面向区块链底层平台、智能合约、可信计算和分布式应用。',
     'high', 'medium', 130, 1, NULL, NULL, 0, 0, 1, 0, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>区块链工程研究分布式账本、共识机制、智能合约和可信应用系统，培养区块链平台开发与应用落地人才。</p><h3>核心方向</h3><p>密码学基础、分布式系统、共识算法、智能合约、联盟链平台、链上数据分析、可信应用开发和区块链安全。</p>',
     17, NOW(), NOW(), 0),
    ('cryptography_science_tech_root', NULL, '密码科学与技术', '计算机类（0809）', 60,
     '080918TK，特设控制布点专业，面向密码理论、密码工程、密码应用和安全基础设施。',
     'high', 'high', 150, 1, NULL, NULL, 0, 0, 1, 1, NULL, NULL, NULL,
     '<h3>专业概述</h3><p>密码科学与技术是网络空间安全的重要基础，面向密码算法、密码协议、密码工程实现和密码应用安全。</p><h3>核心方向</h3><p>数论与代数基础、密码学、密码协议、密码工程、密钥管理、密码应用安全、隐私保护计算和安全基础设施。</p>',
     18, NOW(), NOW(), 0)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    parentId = VALUES(parentId),
    category = VALUES(category),
    symbolSize = VALUES(symbolSize),
    description = VALUES(description),
    difficulty = VALUES(difficulty),
    importance = VALUES(importance),
    estimatedHours = VALUES(estimatedHours),
    teachingWeek = VALUES(teachingWeek),
    isCore = VALUES(isCore),
    isKeyPoint = VALUES(isKeyPoint),
    learningContent = VALUES(learningContent),
    sortOrder = VALUES(sortOrder),
    updateTime = NOW(),
    isDelete = 0;

COMMIT;
